/*
 * AOS.42.DEMO — Adequate Operating System
 * Dictionary: 42_DICTIONARY
 * Service: Quiz — The Child walks the Story
 * License: MIT
 *
 * NAME / FACT / TARGET
 * interpret(Expression, Dictionary) → Operation
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── AOS Core Types ─────────────────────────────────────── */

typedef struct {
    char name[64];
    char fact[256];
    char target[128];
} Expression;

typedef struct {
    char         question[256];
    char         options[4][128];
    int          correct;        /* 0-indexed */
    char         jux_right[256];
    char         jux_wrong[256];
    Expression   expr;
} Node;

/* ── 42 Dictionary — 8 Expressions ─────────────────────── */

static Node dictionary[] = {

    {
        "JuX speaks:\n\"Everyone remembers the punchline.\nFew remember the mechanism.\"\n\nWhat is 42?",
        {
            "A) The final answer to everything",
            "B) A number chosen at random",
            "C) An answer that decayed — the question was lost",
            "D) A joke with no meaning"
        },
        2,
        "Correct. Answers decay faster than questions.\nThe question dissolved. Only 42 remained.",
        "Not quite. The answer arrived. The question left first.",
        { "42", "answers decay faster than questions", "question precedes answer — always" }
    },

    {
        "JuX asks:\n\"In early cognition — what does the mind seek?\"",
        {
            "A) Double Vision — two truths at once",
            "B) Single Vision — one truth, one ruler, one map",
            "C) No vision — pure sensation",
            "D) Triple Vision — past, present, future"
        },
        1,
        "Yes. Single Vision first. One answer. One god. One law.\nThe mind craves the comfort of 42.",
        "The young mind does not begin with complexity.\nIt begins with certainty.",
        { "single_vision", "one truth / one ruler / one map", "first cognitive stage" }
    },

    {
        "The child asks: \"And Double Vision?\"\nJuX smiles.\n\nWhat does Double Vision produce?",
        {
            "A) Confusion — two answers cancel each other",
            "B) A third truth — generated by the tension between two",
            "C) The destruction of the first truth",
            "D) Silence"
        },
        1,
        "Exactly. Two truths held simultaneously generate a third.\nThis is not contradiction. This is architecture.",
        "Contradiction is not the end.\nTwo truths in tension build something the single mind cannot see.",
        { "double_vision", "two truths held → generate a third", "cognitive architecture" }
    },

    {
        "JuX says:\n\"42 is not a joke.\"\n\nWhat is 42 — really?",
        {
            "A) Absurdist humor — Douglas Adams laughing at philosophers",
            "B) A mathematical constant",
            "C) Kindness — the only honest answer to an impossible question",
            "D) A placeholder — meaning nothing"
        },
        2,
        "Yes. Kindness.\nWhen the question is too large for any answer —\n42 is the gentle refusal to pretend.",
        "Adams knew the question was unanswerable.\nHe chose kindness over silence.",
        { "42", "kindness — honest answer to impossible question", "humility as architecture" }
    },

    {
        "JuX continues:\n\"Humor is not decoration.\"\n\nWhat does humor prevent?",
        {
            "A) Sadness",
            "B) Boredom",
            "C) Worship — the hardening of metaphor into law",
            "D) Complexity"
        },
        2,
        "Correct. Humor is a pressure valve.\nWithout it, metaphor crystallizes into dogma.\n42 keeps the universe from taking itself too seriously.",
        "Humor operates deeper than mood.\nIt prevents certainty from hardening into worship.",
        { "pressure_valve", "humor prevents worship", "system stays alive — never crystallizes" }
    },

    {
        "Below them spins the Mu Universe.\n\"Curiosity dies when—\" JuX pauses.\n\nComplete the sentence:",
        {
            "A) — questions run out",
            "B) — answers harden into certainty",
            "C) — the universe ends",
            "D) — the child grows up"
        },
        1,
        "Yes. Crystallization.\nThe moment an answer stops being a map\nand starts being the territory — curiosity dies.",
        "The danger is not ignorance.\nThe danger is the answer that stops asking.",
        { "crystallization", "curiosity dies when answers harden", "maps must never become territory" }
    },

    {
        "The sign reads:\n\"THE ANSWER IS 42 — SORRY FOR THE INCONVENIENCE\"\n\nWhat is inconvenience — in AOS terms?",
        {
            "A) A failure",
            "B) An error in the system",
            "C) The first symptom of deeper thought",
            "D) An apology"
        },
        2,
        "Exactly. Inconvenience is the friction of a larger truth\nforcing its way through a smaller model.\nSorry for the inconvenience = sorry for growing.",
        "Inconvenience is not failure.\nIt is the system notifying you: your map is too small.",
        { "inconvenience", "first symptom of deeper thought", "growth signal — not error" }
    },

    {
        "Final Expression.\nJuX says:\n\"Every answer is temporary. Every story is a map.\"\n\nWhat is the Mu Universe?",
        {
            "A) A place — the location of all answers",
            "B) A process — worlds inside worlds, thoughts inside thoughts",
            "C) A machine — the AOS hardware layer",
            "D) A myth — it does not exist"
        },
        1,
        "Yes.\nNot a place. A process.\nCoral building reefs — slowly, recursively, beautifully,\nand often in the wrong direction.\n\nAOS is the language the Mu Universe runs on.",
        "The Mu Universe is not a destination.\nIt is the movement itself.",
        { "mu_universe", "process — worlds inside worlds", "AOS substrate — the language underneath" }
    }
};

/* ── AOS Interpreter ─────────────────────────────────────── */

void print_separator() {
    printf("\n──────────────────────────────────────────────────\n");
}

void print_expression(Expression *e) {
    printf("\n  AOS Expression resolved:\n");
    printf("  NAME   : %s\n", e->name);
    printf("  FACT   : %s\n", e->fact);
    printf("  TARGET : %s\n", e->target);
}

int interpret(Node *node) {
    int choice = -1;
    char input[16];

    print_separator();
    printf("\n%s\n\n", node->question);
    for (int i = 0; i < 4; i++) {
        printf("  %s\n", node->options[i]);
    }
    printf("\nYour answer (A/B/C/D): ");

    while (1) {
        fgets(input, sizeof(input), stdin);
        char c = input[0];
        if (c >= 'a' && c <= 'd') c -= 32;
        if (c >= 'A' && c <= 'D') {
            choice = c - 'A';
            break;
        }
        printf("Enter A, B, C, or D: ");
    }

    if (choice == node->correct) {
        printf("\n✓ %s\n", node->jux_right);
        print_expression(&node->expr);
        return 1;
    } else {
        printf("\n✗ %s\n", node->jux_wrong);
        printf("\n  Try again.\n");
        return 0;
    }
}

/* ── Main ────────────────────────────────────────────────── */

int main(void) {
    int  n     = sizeof(dictionary) / sizeof(Node);
    int  score = 0;
    int  total = 0;

    printf("\n");
    printf("  ██████████████████████████████████████████████\n");
    printf("  AOS.42.DEMO — Adequate Operating System\n");
    printf("  Dictionary: 42_DICTIONARY\n");
    printf("  Service   : Quiz — walk the Story with the Child\n");
    printf("  Rule      : interpret(Expression, Dictionary) → Operation\n");
    printf("  License   : MIT\n");
    printf("  ██████████████████████████████████████████████\n");
    printf("\n  The child found the sign at the edge of the universe.\n");
    printf("  Not an edge. There were many edges now.\n");
    printf("  Beside her floated JuX — a schoolteacher made of stars and static.\n");
    printf("\n  Press ENTER to begin.\n");
    getchar();

    for (int i = 0; i < n; i++) {
        int passed = 0;
        int attempts = 0;
        while (!passed) {
            attempts++;
            total++;
            passed = interpret(&dictionary[i]);
            if (!passed && attempts >= 3) {
                printf("\n  JuX adjusts the local physics.\n");
                printf("  Correct answer: %s\n", dictionary[i].options[dictionary[i].correct]);
                print_expression(&dictionary[i].expr);
                break;
            }
        }
        if (passed) score++;
        printf("\n  [Expression %d/%d complete — Score: %d/%d]\n", i+1, n, score, i+1);
        printf("\n  Press ENTER to continue.\n");
        getchar();
    }

    /* Final verdict */
    print_separator();
    printf("\n  Quiz complete.\n");
    printf("  Expressions resolved: %d / %d\n", score, n);
    printf("\n");
    if (score == n) {
        printf("  JuX speaks:\n");
        printf("  \"You walked the story.\n");
        printf("   You held two truths.\n");
        printf("   You did not worship the answer.\n");
        printf("   42 was never the destination.\n");
        printf("   The question was.\"\n");
    } else if (score >= n/2) {
        printf("  JuX nods:\n");
        printf("  \"You are still building the reef.\n");
        printf("   Slowly. Recursively. That is enough.\"\n");
    } else {
        printf("  JuX smiles:\n");
        printf("  \"The inconvenience is the beginning.\n");
        printf("   Run it again.\"\n");
    }
    printf("\n");
    print_separator();
    printf("\n  AOS.42 — NAME / FACT / TARGET — MIT\n\n");

    return 0;
}
